# Generated by Django 4.1.1 on 2022-09-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="modified",
            new_name="modified_at",
        ),
    ]
